### PR TITLE
update choo to v6

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Auth0 recently published [an article](https://auth0.com/blog/preact-authentication-tutorial/) citing this benchmark, which still uses choo v1.3. Given it's now a year and 5 major versions later, I figured I'd update this bench. Hopefully this all OK. Thanks!

### CODE REVIEW

**Comment by developit** [comment]
Hmm - seems to be missing the source?

**Comment by yoshuawuyts** [comment]
Don't believe there was a source checked in to begin with? I just used the
example we got in-source
https://github.com/yoshuawuyts/choo/tree/master/example

**Comment by developit** [comment]
Just tried the demo locally and it's only ever appending a single todo item, which is causing the perf number to be quite skewed.

> **edit:** _I jsbeautify'd the choo demo, and I think it's the input debouncing that is causing this issue - the debounce never kicks in because the benchmark removes all items synchronously. For the bench to be accurate, there would need to be some flag that turns that feature off_.

Here's Choo:
30f2ad2aa498d72e2b40c35edd424e83

Here's Preact:
d1a4e13f4b31853d5daf0f95eace88e9

**Comment by developit** [comment]
It's actually a beef I have with this benchmark - it doesn't have any assertions to make sure things are running to the spec of the bench. This repo is actually just a fork that updated preact from the original - how cycle repeats itself, haha.

**Comment by yoshuawuyts** [comment]
Lol yeah dang, like I said on twitter: maybe should just call it a day then
and point people to another bench? Saves us all time maintaining, and
(hopefully) prevents further misquoting haha. You know any good benches we
could point folks to?

**Comment by developit** [comment]
js-framework-benchmark is fairly solid since it produces really reliable numbers (uses WebDriver to run Chrome around a benchmark) - but it doesn't validate either.  UIBench seems to be the only one that actually asserts on the resulting DOM, but it's hugely slanted towards "perf grind" type stuff, not very real-world.

Benchmarks in general are kinda horrible and I've basically given up on trying to keep up with things - I run them myself to track Preact's progress and catch bugs, but I try to avoid making any comparisons across libs.  I've had a few cases where I thought something was a massive performance gain, and it turned out to just be deferring work until after the timed region of a benchmark.  Stuff like that is too infuriating :P

-edit- apologies for the dual convo here & twitter

**Comment by yoshuawuyts** [comment]
lmao, yeah feel we're very much on the same page about this stuff. I'll
keep tabs on both those benches then (: Closing this PR

**Pull request closed without merging**
